// Generated by dedot cli

import type { AccountId32Like, AccountId32 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type OracleTokenPriceData = {
  price: bigint;
  marketCap: bigint;
  volume24h: bigint;
  timestamp: bigint;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Oracle = {
  tokenData: {
    get(arg: AccountId32Like): Promise<OracleTokenPriceData | undefined>;
  };
  authorizedUpdaters: {
    get(arg: AccountId32Like): Promise<boolean | undefined>;
  };
  validationConfig: OracleValidationConfig;
  owner: AccountId32;
  paused: boolean;
};

export type OracleValidationConfig = {
  maxDeviationBp: number;
  stalenessThreshold: bigint;
  minUpdateInterval: bigint;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type SharedError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance";

export type InkEnvNoChainExtension = null;
